### PR TITLE
update autoprefixer to 8.6.3 & postcss to 6.0.22 (fix #33)

### LINKED ISSUE #33: Update Autoprefixer
Autoprefixer's on version 8.  It'd be nice to use the latest.

### PR DESCRIPTION
**Pull request by calvinjuarez**
I'm not sure what version to bump (major, minor, patch), and I could use help figuring out what the new minimum Node version requirement is (I tested with 8.11.3).

### CODE REVIEW

**Comment by matthew-dean** [comment]
Did you mean the minimum Node version requirement for Less?

**Comment by matthew-dean** [comment]
AFAIK package.lock shouldn't be committed.

**Comment by calvinjuarez** [comment]
I think the lock file is meant to be committed.  At least according to the documentation for it at https://docs.npmjs.com/files/package-lock.json.  I can remove it, though.  I'm new to the "lock" idea.

screen shot 2018-06-25 at 14 41 56

**Comment by calvinjuarez** [comment]
> Did you mean the minimum Node version requirement for Less? See: https://github.com/less/less.js/blob/master/.travis.yml

I'm referring to the minimum Node version required by this package, which I guess would be `>=4.0.0`, to match postcss v6's minimum (https://github.com/postcss/postcss/blob/master/package.json#L6).  To be honest, I'm not sure what my confusion was...Ignore that part.

**Comment by calvinjuarez** [comment]
Just wanna bump this plugin's version.  It might be a major bump, since the minimum Node version changed, but other than that all old code should work.  Minor?

**Comment by matthew-dean** [comment]
It's fine to bump this a major version.

**Comment by calvinjuarez** [comment]
@matthew-dean  Do I need anyone's permission to merge this?  Also how would I publish it to npm?

**Comment by matthew-dean** [comment]
@calvinjuarez Anyone's permission? Nope. Go for it.

NPM publish? Hmm, you might need @lukeapage's support. I don't have publish permissions for this repo. I just set up a `lesscss` NPM org, but I'd have to start adding repos I have publish permissions for. Currently that's just `less/less.js`

**Comment by lukeapage** [comment]
@matthew-dean I will try and give you owner rights on all npm packages. Feel free to message me on Twitter if you need anything else.

**Comment by calvinjuarez** [comment]
@lukeapage @matthew-dean  Merging now.  Once we get npm worked out we can publish and get this into people's hands.

**Pull request merged**
